enum CssClasses {
  PRODUCTS = 'product__container',
  CARD = 'product__card',
  IMAGE = 'product__image',
  NAME = 'product__name',
  DESCRIPTION = 'product__description',
  PRICE = 'product__price',
  DISCOUNT = 'product__discount',
  DISCOUNTED = 'product__discounted-price',
  CANCELPRICE = 'product__price--cancel',
  NOPICTURE = 'product__image--no-picture',
  FILTERS = 'filter__container',
  RESETFILTERSBUTTON = 'filter__button-reset',
  FILTERPRICE = 'filter__price',
  FILTERBRAND = 'filter__brand',
  FILTERCOLOR = 'filter__color',
  FILTERSIZE = 'filter__size',
  FILTERMATERIAL = 'filter__material',
  SORT = 'sort__container',
  SORTNAME = 'sort__name',
  SORTPRICE = 'sort__price',
  RESETSORTINGBUTTON = 'sort__button-reset',
  RESETSEARCHBUTTON = 'search__button-reset',
  SEARCHBUTTON = 'search__button-search',
  SEARCH = 'search__container',
}

export default CssClasses;
