export const filterColors = [
  'Ash',
  'Athletic Heather',
  'Black',
  'Black Denim',
  'Black Heather',
  'Brown',
  'Charcoal Black Triblend',
  'Cotton Candy',
  'Heather Dust',
  'Light Denim',
  'Navy / White',
  'Purple',
  'Silver',
  'Sky',
  'Soft Cream',
  'True Royal',
  'White',
  'Yellow',
];
export const filterMaterials = [
  '100% acrylic',
  '100% cotton',
  '100% polyester',
  'Ceramic',
  'Enamel SPCC + 304 Stainless Steel Rim',
  'Hardboard and cork',
  'Polyester',
  'Poly-cotton blend',
  'Rubber',
  'Sustainable fabric',
  'TPU',
  'Tri-blend',
];
export const filterPrices = ['0-10$', '10-20$', '20-30$', '30-40$', '40-50$', '50-100$'];
export const filterSizes = [
  'One Size',
  '50″×60″',
  '2',
  '3.74″×3.74″',
  '11oz',
  '12oz',
  '13″',
  '2XS',
  'XS',
  'S',
  'S/M',
  'M',
  'L',
  'XL',
  '2XL',
  '3XL',
];
export const filterBrands = [
  'AirPods',
  'Bella + Canvas',
  'Capstone',
  'Cotton Heritage',
  'Econscious',
  'Fabric and rubber',
  'Flexfit',
  'Gildan',
  'iPhone 11',
  'Otto Cap',
  'Port Authority',
  'Rabbit Skins',
  'Shaka Wear',
  'Sportsman',
  'Threadfast Apparel',
  'Yupoong',
];
