enum CssClasses {
  BODY = 'user-profile__table-body',
  ROW = 'row-module',
  TYPE_OF_ADDRESS = 'address-type',
  SHIPPING = 'shipping',
  BILLING = 'billing',
  DEFAULT_SHIPPING = 'default-shipping',
  DEFAULT_BILLING = 'default-billing',
  HIDDEN = 'hidden',
  ICON_BOX = 'user-profile__icon-box',
  ICON = 'user-profile__icon',
  CONTAINER = 'user-profile__container',
  WRAPPER_WRITE = 'user-profile__icon-wrapper_write',
  WRAPPER_CANCEL = 'user-profile__icon-wrapper_cancel',
  EDIT_MODE = 'edit-mode',
  CELL = 'info__cell',
  OVERLAY = 'user-profile__overlay',
  MODAL = 'user-profile__modal-main',
  NAME = 'container_name',
  PASSWORD = 'container_password',
  ADDRESS = 'container_address',
  ADD_BUTTON = 'user-profile__button-box',
  SUBMIT_BUTTON = 'submit-button',
  EDIT_MODE_FLAG = 'addresses__info',
  FIELD = 'input-module__input-field',
}

export default CssClasses;
